-- 1. Зависимые таблицы (с FK на другие таблицы)
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS film_directors;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS review_ratings;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS events;

-- 2. Основные таблицы (на которые ссылаются)
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS genres;

-- 3. Справочные таблицы (без зависимостей)
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS directors;

-- Существующие таблицы (без изменений)
CREATE TABLE IF NOT EXISTS mpa (
    id INT PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INT,
    mpa_id INT REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id INT NOT NULL REFERENCES genres (id),
    PRIMARY KEY (film_id, genre_id)
);

-- 1. Добавление режиссёров (add-director)
CREATE TABLE IF NOT EXISTS directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
    film_id BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    director_id BIGINT NOT NULL REFERENCES directors (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);

-- 2. Функциональность «Отзывы» (add-reviews)
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL,  -- true = положительный, false = негативный
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    film_id BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_ratings (
    review_id BIGINT NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_like BOOLEAN NOT NULL,      -- true = лайк, false = дизлайк
    PRIMARY KEY (review_id, user_id)
);

-- 3. Функциональность «Лента событий» (add-feed)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT NOT NULL,          -- UNIX timestamp
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_type VARCHAR(10) NOT NULL,  -- 'LIKE', 'REVIEW', 'FRIEND'
    operation VARCHAR(10) NOT NULL,     -- 'ADD', 'UPDATE', 'REMOVE'
    entity_id BIGINT NOT NULL            -- ID сущности (film_id, review_id и т.п.)
);